In [1]:
include("functions.jl")

function f(x)
    theta = [.8; .5; .5]
    c = theta[1]*exp(theta[2]*x) + (1-theta[1])*exp(-theta[3]*x)
    f = [1; (exp(theta[2]*x) - exp(-theta[3]*x))/c; theta[1]*x*exp(theta[2]*x)/c; -(1-theta[1])*x*exp(-theta[3]*x)/c]
    return f
end

ex1 = example(4,[0,10],f)

example(4, [0, 10], f)

In [2]:
misocp(30,4,ex1)
solve!(prob, MosekSolver())

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 664             
  Cones                  : 127             
  Scalar variables       : 838             
  Matrix variables       : 0               
  Integer variables      : 31              

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.01
Presolved problem: 571 variables, 301 constraints, 1322 non-zeros
Presolved problem: 0 general integer, 31 binary, 540 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        0        0        NA                   -1.7656058037e-01    NA          0.1   
0        1        0        0        -4.9929574233e-07    -1.7656058037e-01    3.54e+07    0.2   
0        1        0        0        -6.5365850617e-06    -1

In [3]:
w.value[w.value.>0 ]

4-element Array{Float64,1}:
 0.25000299427613637
 0.2499436319668781 
 0.25004020425027385
 0.25001316928697337

In [4]:
x[getindex.(findall(x->x>0, w.value),1)]

4-element Array{Float64,1}:
  0.0
  1.0
  4.0
 10.0

In [5]:
prob.optval^4

0.0009717256165995844

In [6]:
n = [16; 32; 64; 128; 256; 512; 1024]
save = zeros(length(n), 4*2+2)
for i in 1:length(n)
    t1 = time()
    misocp(n[i],4,ex1)
    solve!(prob, MosekSolver())
    t2 = time()
    cc = w.value[w.value.>0]
    cc = [cc; x[getindex.(findall(x->x>0, w.value),1)]]
    cc = [cc; (prob.optval^4/0.0009723832732216562)^(1/4)]
    cc = [cc; t2-t1]
    save[i,:] = cc
end

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 384             
  Cones                  : 71              
  Scalar variables       : 474             
  Matrix variables       : 0               
  Integer variables      : 17              

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.00
Presolved problem: 319 variables, 175 constraints, 734 non-zeros
Presolved problem: 0 general integer, 17 binary, 302 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        0        0        NA                   -1.7301531219e-01    NA          0.0   
0        1        0        0        -1.6996159468e-06    -1.7301531219e-01    1.02e+07    0.0   
0        1        0        0        -1.7294353978e-01    -1.

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 5184            
  Cones                  : 1031            
  Scalar variables       : 6714            
  Matrix variables       : 0               
  Integer variables      : 257             

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.12
Presolved problem: 4639 variables, 2335 constraints, 10814 non-zeros
Presolved problem: 0 general integer, 257 binary, 4382 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        0        0        NA                   -1.7734357126e-01    NA          0.3   
0        1        0        0        -2.4185454381e-05    -1.7734357126e-01    7.33e+05    0.6   
0        1        0        0        -1.7659982077e-01 

In [7]:
display(save[:,1:4])
display(save[:,5:10])

7×4 Array{Float64,2}:
 0.250007  0.249995  0.249985  0.250013
 0.250002  0.24991   0.250068  0.25002 
 0.249999  0.249976  0.250019  0.250006
 0.250056  0.24979   0.250019  0.250136
 0.250178  0.249928  0.249633  0.250261
 0.250237  0.249539  0.249961  0.250263
 0.250403  0.250021  0.249061  0.250515

7×6 Array{Float64,2}:
 0.0  1.25      4.375    10.0  0.979366   0.233294
 0.0  0.9375    4.0625   10.0  0.999225   0.260047
 0.0  0.9375    3.90625  10.0  0.999423   0.451119
 0.0  0.9375    3.98438  10.0  0.999874   2.15225 
 0.0  0.976563  3.98438  10.0  1.00007    4.29234 
 0.0  0.976563  3.96484  10.0  1.00047   14.6578  
 0.0  0.966797  3.96484  10.0  1.00117   48.198   