In [1]:
include("functions.jl")

function f(x)
    theta = [3,-5,0]
    c = exp(theta[1]+theta[2]*(x-theta[3])^2)
    f = [1,(x-theta[3])^2,2*theta[2]*(theta[3]-x) ]
    return sqrt(c)/(1+c)*f
end

ex1 = example(3, [-1,1], f)

example(3, [-1, 1], f)

In [6]:
misocp(200,3,ex1)
solve!(prob, MosekSolver())

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 3249            
  Cones                  : 606             
  Scalar variables       : 4045            
  Matrix variables       : 0               
  Integer variables      : 201             

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.06
Presolved problem: 2825 variables, 1423 constraints, 6248 non-zeros
Presolved problem: 0 general integer, 201 binary, 2624 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        0        0        NA                   -3.7715076818e-01    NA          0.2   
0        1        0        0        -9.0290236443e-05    -3.7715076818e-01    4.18e+05    0.7   
0        1        0        0        -1.0499650813e-04  

14044    14037    513      38       -3.7168696327e-01    -3.7446236503e-01    0.75        107.9 
14545    14538    550      31       -3.7168696327e-01    -3.7426811757e-01    0.69        111.4 
15046    15039    545      45       -3.7168696327e-01    -3.7426266689e-01    0.69        114.7 
15519    15512    542      32       -3.7168696327e-01    -3.7414738089e-01    0.66        119.1 
16021    16014    554      31       -3.7168696327e-01    -3.7405929409e-01    0.64        124.4 
16524    16517    583      35       -3.7168696327e-01    -3.7393151182e-01    0.60        129.4 
17020    17013    607      41       -3.7168696327e-01    -3.7391542506e-01    0.60        132.7 
17515    17508    614      23       -3.7168696327e-01    -3.7391542506e-01    0.60        137.0 
18015    18008    624      53       -3.7168696327e-01    -3.7380285275e-01    0.57        140.7 
18514    18507    629      63       -3.7168696327e-01    -3.7380285275e-01    0.57        144.6 
19008    19001    645      47 

In [7]:
w.value[w.value.>0 ]

3-element Array{Float64,1}:
 0.3333327926659296
 0.3333925730285715
 0.3332746241914952

In [8]:
x[getindex.(findall(x->x>0, w.value),1)]

3-element Array{Float64,1}:
 -0.85
  0.54
  0.95

In [9]:
re3 = prob.optval^4

0.019085753691946847

In [5]:
re4 = prob.optval^4

0.02023281846241203

In [10]:
re3 / re4

0.9433067235493579

In [6]:
prob.optval^4/1617.5895386975224

1.2502757265267228e-5

In [7]:
n = [16; 32; 64; 128; 256; 512; 1024]
save = zeros(length(n), 4*2+2)
for i in 1:length(n)
    t1 = time()
    misocp(n[i],4,ex1)
    solve!(prob, MosekSolver())
    t2 = time()
    cc = w.value[w.value.>0]
    cc = [cc; x[getindex.(findall(x->x>0, w.value),1)]]
    cc = [cc; (prob.optval^4/0.02023431778515896)^(1/3)]
    cc = [cc; t2-t1]
    save[i,:] = cc
end

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 305             
  Cones                  : 54              
  Scalar variables       : 365             
  Matrix variables       : 0               
  Integer variables      : 17              

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.00
Presolved problem: 249 variables, 135 constraints, 544 non-zeros
Presolved problem: 0 general integer, 17 binary, 232 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        0        0        NA                   -3.7040808147e-01    NA          0.0   
0        1        0        0        -4.0344802663e-05    -3.7040808147e-01    9.18e+05    0.0   
0        1        0        0        -6.5467305621e-05    -3.

0        1        0        0        -3.7715500846e-01    -3.7715544205e-01    1.15e-04    0.5   
An optimal solution satisfying the relative gap tolerance of 1.00e-02(%) has been located.
The relative gap is 1.15e-04(%).

Objective of best integer solution : -3.771550084563e-01     
Best objective bound               : -3.771554420503e-01     
Construct solution objective       : Not employed
Construct solution # roundings     : 0
User objective cut value           : 0
Number of cuts generated           : 0
Number of branches                 : 0
Number of relaxations solved       : 1
Number of interior point iterations: 27
Number of simplex iterations       : 0
Time spend presolving the root     : 0.02
Time spend in the heuristic        : 0.00
Time spend in the sub optimizers   : 0.00
  Time spend optimizing the root   : 0.05
Mixed integer optimizer terminated. Time: 0.55

Optimizer terminated. Time: 0.55    


Integer solution solution summary
  Problem status  : PRIMAL_FEASIBLE
  Sol

In [8]:
display(save[:,1:4])
display(save[:,5:10])

7×4 Array{Float64,2}:
 0.316456  0.183544  0.183544  0.316456
 0.285412  0.214588  0.214588  0.285412
 0.298526  0.22942   0.176512  0.295542
 0.296114  0.203886  0.203886  0.296114
 0.296105  0.203895  0.203895  0.296105
 0.296138  0.203862  0.203862  0.296138
 0.296591  0.203409  0.203409  0.296591

7×6 Array{Float64,2}:
 -0.875     -0.5       0.5       0.875     0.976003   0.219073
 -0.9375    -0.625     0.625     0.9375    0.996969   0.194213
 -0.9375    -0.59375   0.59375   0.90625   0.998702   0.945736
 -0.921875  -0.59375   0.59375   0.921875  0.999993   0.768916
 -0.921875  -0.59375   0.59375   0.921875  0.999994   2.73852 
 -0.921875  -0.59375   0.59375   0.921875  0.999996   6.19783 
 -0.921875  -0.591797  0.591797  0.921875  1.0       19.6881  