In [1]:
include("functions.jl")

function f(x)
    theta = [2,3,0]
    c = exp(theta[1]+theta[2]*(x-theta[3])^2)
    f = [1,(x-theta[3])^2,2*theta[2]*(theta[3]-x) ]
    return sqrt(c)/(1+c)*f
end

ex1 = example(3, [-3,1], f)

example(3, [-3, 1], f)

In [2]:
misocp(100,3,ex1)
solve!(prob, MosekSolver())

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 1649            
  Cones                  : 306             
  Scalar variables       : 2045            
  Matrix variables       : 0               
  Integer variables      : 101             

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.03
Presolved problem: 1425 variables, 723 constraints, 3148 non-zeros
Presolved problem: 0 general integer, 101 binary, 1324 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        0        0        NA                   -8.6857385791e-02    NA          0.2   
0        1        0        0        -1.9173558243e-05    -8.6857385791e-02    4.53e+05    0.3   
0        1        0        0        -8.6856277521e-02   

In [3]:
w.value[w.value.>0 ]

3-element Array{Float64,1}:
 0.3333437507559908 
 0.33331229808391216
 0.33334394976262244

In [4]:
x[getindex.(findall(x->x>0, w.value),1)]

3-element Array{Float64,1}:
 -0.72
  0.0 
  0.72

In [5]:
prob.optval^4

5.691213131134237e-5

In [6]:
n = [16; 32; 64; 128; 256; 512; 1024]
save = zeros(length(n), 3*2+2)
for i in 1:length(n)
    t1 = time()
    misocp(n[i],3,ex1)
    solve!(prob, MosekSolver())
    t2 = time()
    cc = w.value[w.value.>0]
    cc = [cc; x[getindex.(findall(x->x>0, w.value),1)]]
    cc = [cc; (prob.optval^4/5.69464649495885e-5)^(1/3)]
    cc = [cc; t2-t1]
    save[i,:] = cc
end

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 305             
  Cones                  : 54              
  Scalar variables       : 365             
  Matrix variables       : 0               
  Integer variables      : 17              

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.00
Presolved problem: 249 variables, 135 constraints, 544 non-zeros
Presolved problem: 0 general integer, 17 binary, 232 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        0        0        NA                   -8.6728803457e-02    NA          0.0   
0        1        0        0        -1.3983564370e-05    -8.6728803457e-02    6.20e+05    0.1   
0        1        0        0        -8.6728855138e-02    -8.

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 4145            
  Cones                  : 774             
  Scalar variables       : 5165            
  Matrix variables       : 0               
  Integer variables      : 257             

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.09
Presolved problem: 3609 variables, 1815 constraints, 7984 non-zeros
Presolved problem: 0 general integer, 257 binary, 3352 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        0        0        NA                   -8.6860627340e-02    NA          0.2   
0        1        0        0        -1.1049657501e-05    -8.6860627340e-02    7.86e+05    0.7   
0        1        0        0        -8.6854827565e-02  

In [7]:
save

7×8 Array{Float64,2}:
 0.333291  0.333419  0.33329   -0.75      0.0  0.75      0.997844   0.125898
 0.333346  0.333306  0.333348  -0.75      0.0  0.75      0.997844   0.209588
 0.333308  0.333386  0.333307  -0.75      0.0  0.75      0.997861   0.701767
 0.333329  0.333343  0.333328  -0.71875   0.0  0.71875   0.99972    0.752924
 0.333324  0.333351  0.333325  -0.734375  0.0  0.734375  0.999777   2.24468 
 0.333346  0.333309  0.333345  -0.726563  0.0  0.726563  1.0        6.03166 
 0.333311  0.333371  0.333317  -0.726563  0.0  0.726563  1.00076   24.4206  