In [1]:
include("functions.jl")

function f(x)
    theta = [.2; .2; .2]
    c = theta[1]*exp(theta[2]*x) + (1-theta[1])*exp(-theta[3]*x)
    f = [1; (exp(theta[2]*x) - exp(-theta[3]*x))/c; theta[1]*x*exp(theta[2]*x)/c; -(1-theta[1])*x*exp(-theta[3]*x)/c]
    return f
end

ex1 = example(4,[0,10],f)

example(4, [0, 10], f)

In [2]:
misocp(30,4,ex1)
solve!(prob, MosekSolver())

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 664             
  Cones                  : 127             
  Scalar variables       : 838             
  Matrix variables       : 0               
  Integer variables      : 31              

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.01
Presolved problem: 571 variables, 301 constraints, 1322 non-zeros
Presolved problem: 0 general integer, 31 binary, 540 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        0        0        NA                   -6.3589423884e-01    NA          0.1   
0        1        0        0        -7.4558054066e-06    -6.3589423884e-01    8.53e+06    0.1   
0        1        0        0        -6.3589432729e-01    -6

In [3]:
w.value[w.value.>0 ]

4-element Array{Float64,1}:
 0.25000504911328064
 0.24997450366622906
 0.25001771189618865
 0.2500027323739299 

In [4]:
x[getindex.(findall(x->x>0, w.value),1)]

4-element Array{Float64,1}:
  0.0               
  2.6666666666666665
  6.666666666666667 
 10.0               

In [5]:
prob.optval^4

0.16350829989818524

In [6]:
n = [16; 32; 64; 128; 256; 512; 1024]
save = zeros(length(n), 4*2+2)
for i in 1:length(n)
    t1 = time()
    misocp(n[i],4,ex1)
    solve!(prob, MosekSolver())
    t2 = time()
    if length(w.value[w.value.>0]) != 4
        continue
    end
    cc = w.value[w.value.>0]
    cc = [cc; x[getindex.(findall(x->x>0, w.value),1)]]
    cc = [cc; (prob.optval^4/0.16356828710579696)^(1/4)]
    cc = [cc; t2-t1]
    save[i,:] = cc
end

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 384             
  Cones                  : 71              
  Scalar variables       : 474             
  Matrix variables       : 0               
  Integer variables      : 17              

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.00
Presolved problem: 319 variables, 175 constraints, 734 non-zeros
Presolved problem: 0 general integer, 17 binary, 302 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        0        0        NA                   -6.3372576890e-01    NA          0.0   
0        1        0        0        -1.7539000731e-07    -6.3372576890e-01    3.61e+08    0.0   
0        1        0        0        -6.1248368805e-07    -6.

An optimal solution satisfying the relative gap tolerance of 1.00e-02(%) has been located.
The relative gap is 0.00e+00(%).
An optimal solution satisfying the absolute gap tolerance of 0.00e+00 has been located.
The absolute gap is 0.00e+00.

Objective of best integer solution : -6.359473555967e-01     
Best objective bound               : -6.359472243953e-01     
Construct solution objective       : Not employed
Construct solution # roundings     : 0
User objective cut value           : 0
Number of cuts generated           : 0
Number of branches                 : 0
Number of relaxations solved       : 1
Number of interior point iterations: 23
Number of simplex iterations       : 0
Time spend presolving the root     : 0.03
Time spend in the heuristic        : 0.00
Time spend in the sub optimizers   : 0.00
  Time spend optimizing the root   : 0.05
Mixed integer optimizer terminated. Time: 0.61

Optimizer terminated. Time: 0.62    


Integer solution solution summary
  Problem status  : 

In [7]:
display(save[:,1:4])
display(save[:,5:10])

7×4 Array{Float64,2}:
 0.250004  0.249991  0.250002  0.250004
 0.249999  0.249992  0.250004  0.250005
 0.250002  0.249991  0.250007  0.25    
 0.25      0.25      0.25      0.249999
 0.250001  0.250002  0.249999  0.249998
 0.249995  0.250004  0.250011  0.249989
 0.249995  0.250003  0.250009  0.249993

7×6 Array{Float64,2}:
 0.0  2.5      6.875    10.0  0.996285   0.212479
 0.0  2.5      6.5625   10.0  0.998014   0.396101
 0.0  2.65625  6.71875  10.0  0.999992   0.402107
 0.0  2.65625  6.71875  10.0  0.999992   1.01464 
 0.0  2.65625  6.71875  10.0  0.999992   2.54376 
 0.0  2.65625  6.69922  10.0  0.999997   7.58974 
 0.0  2.65625  6.70898  10.0  0.999999  26.558   

In [8]:
save[:,5:8]

7×4 Array{Float64,2}:
 0.0  2.5      6.875    10.0
 0.0  2.5      6.5625   10.0
 0.0  2.65625  6.71875  10.0
 0.0  2.65625  6.71875  10.0
 0.0  2.65625  6.71875  10.0
 0.0  2.65625  6.69922  10.0
 0.0  2.65625  6.70898  10.0