In [1]:
include("functions.jl")

function f(x)
    theta = [-2.163, -0.1]
    c = 1-exp(-30*exp(theta[1]+theta[2]*x))
    f = [1,x]
    return sqrt(c)*f
end

ex1 = example(2,[0,1],f)

example(2, [0, 1], f)

In [2]:
misocp(30,2,ex1)
solve!(prob, MosekSolver())

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 387             
  Cones                  : 63              
  Scalar variables       : 444             
  Matrix variables       : 0               
  Integer variables      : 31              

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.00
Presolved problem: 315 variables, 164 constraints, 660 non-zeros
Presolved problem: 0 general integer, 31 binary, 284 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        0        0        NA                   -4.8102200938e-01    NA          0.1   
0        1        0        0        -4.8102204974e-01    -4.8102204974e-01    0.00e+00    0.1   
An optimal solution satisfying the relative gap tolerance of

In [3]:
w.value[w.value.>0 ]

2-element Array{Float64,1}:
 0.5000007770531683 
 0.49999922294683175

In [4]:
x[getindex.(findall(x->x>0, w.value),1)]

2-element Array{Float64,1}:
 0.0
 1.0

In [5]:
prob.optval^4

0.053537728184851884

In [6]:
function f(x)
    theta = [-2.163, -0.1]
    c = 1-exp(-30*exp(theta[1]+theta[2]*x))
    f = [1,x]
    return sqrt(c)*f
end
ex1 = example(2,[0,1],f)

n = [16; 32; 64; 128; 256; 512; 1024]
save = zeros(length(n), 2*2+2)
for i in 1:length(n)
    t1 = time()
    misocp(n[i],2,ex1)
    solve!(prob, MosekSolver())
    t2 = time()
    cc = w.value[w.value.>0]
    cc = [cc; x[getindex.(findall(x->x>0, w.value),1)]]
    cc = [cc; (prob.optval^2/0.23138226556240576)^(1/2)]
    cc = [cc; t2-t1]
    save[i,:] = cc
end

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 219             
  Cones                  : 35              
  Scalar variables       : 248             
  Matrix variables       : 0               
  Integer variables      : 17              

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.00
Presolved problem: 175 variables, 94 constraints, 366 non-zeros
Presolved problem: 0 general integer, 17 binary, 158 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        0        0        NA                   -4.8102201027e-01    NA          0.0   
0        1        0        0        -4.8102204695e-01    -4.8102204695e-01    0.00e+00    0.0   
An optimal solution satisfying the relative gap tolerance of 

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 3099            
  Cones                  : 515             
  Scalar variables       : 3608            
  Matrix variables       : 0               
  Integer variables      : 257             

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.06
Presolved problem: 2575 variables, 1294 constraints, 5406 non-zeros
Presolved problem: 0 general integer, 257 binary, 2318 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        0        0        NA                   -4.8102082260e-01    NA          0.1   
0        1        0        0        -4.8102221161e-01    -4.8102221161e-01    0.00e+00    0.2   
An optimal solution satisfying the relative gap toleran

In [7]:
save

7×6 Array{Float64,2}:
 0.500002  0.499998  0.0  1.0  1.0  0.0488689
 0.5       0.5       0.0  1.0  1.0  0.0648761
 0.500001  0.499999  0.0  1.0  1.0  0.120366 
 0.500001  0.499999  0.0  1.0  1.0  0.235436 
 0.49998   0.50002   0.0  1.0  1.0  0.776041 
 0.500018  0.499982  0.0  1.0  1.0  2.05087  
 0.500033  0.499967  0.0  1.0  1.0  6.85129  

In [8]:
function f(x)
    theta = [-2.163, -0.405]
    c = 1-exp(-30*exp(theta[1]+theta[2]*x))
    f = [1,x]
    return sqrt(c)*f
end
ex1 = example(2,[0,1],f)

n = [16; 32; 64; 128; 256; 512; 1024]
save = zeros(length(n), 2*2+2)
for i in 1:length(n)
    t1 = time()
    misocp(n[i],2,ex1)
    solve!(prob, MosekSolver())
    t2 = time()
    cc = w.value[w.value.>0]
    cc = [cc; x[getindex.(findall(x->x>0, w.value),1)]]
    cc = [cc; (prob.optval^2/0.21780630436463627)^(1/2)]
    cc = [cc; t2-t1]
    save[i,:] = cc
end

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 219             
  Cones                  : 35              
  Scalar variables       : 248             
  Matrix variables       : 0               
  Integer variables      : 17              

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.00
Presolved problem: 175 variables, 94 constraints, 366 non-zeros
Presolved problem: 0 general integer, 17 binary, 158 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        0        0        NA                   -4.6669715169e-01    NA          0.1   
0        1        0        0        -4.6669719754e-01    -4.6669719754e-01    0.00e+00    0.1   
An optimal solution satisfying the relative gap tolerance of 

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 3099            
  Cones                  : 515             
  Scalar variables       : 3608            
  Matrix variables       : 0               
  Integer variables      : 257             

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.09
Presolved problem: 2575 variables, 1294 constraints, 5406 non-zeros
Presolved problem: 0 general integer, 257 binary, 2318 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        0        0        NA                   -4.6669629692e-01    NA          0.2   
0        1        0        0        -4.6669723658e-01    -4.6669723658e-01    0.00e+00    0.4   
An optimal solution satisfying the relative gap toleran

In [9]:
save

7×6 Array{Float64,2}:
 0.500003  0.499997  0.0  1.0  1.0  0.121156 
 0.500007  0.499993  0.0  1.0  1.0  0.0500259
 0.500003  0.499997  0.0  1.0  1.0  0.122531 
 0.50001   0.49999   0.0  1.0  1.0  0.271261 
 0.499991  0.500009  0.0  1.0  1.0  1.23423  
 0.499991  0.500009  0.0  1.0  1.0  2.77288  
 0.5       0.5       0.0  1.0  1.0  8.22621  

In [10]:
function f(x)
    theta = [-2.163, -1.526]
    c = 1-exp(-30*exp(theta[1]+theta[2]*x))
    f = [1,x]
    return sqrt(c)*f
end
ex1 = example(2,[0,1],f)

n = [16; 32; 64; 128; 256; 512; 1024]
save = zeros(length(n), 2*2+2)
for i in 1:length(n)
    t1 = time()
    misocp(n[i],2,ex1)
    solve!(prob, MosekSolver())
    t2 = time()
    cc = w.value[w.value.>0]
    cc = [cc; x[getindex.(findall(x->x>0, w.value),1)]]
    cc = [cc; (prob.optval^2/0.1277079541438674)^(1/2)]
    cc = [cc; t2-t1]
    save[i,:] = cc
end

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 219             
  Cones                  : 35              
  Scalar variables       : 248             
  Matrix variables       : 0               
  Integer variables      : 17              

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.00
Presolved problem: 175 variables, 94 constraints, 366 non-zeros
Presolved problem: 0 general integer, 17 binary, 158 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        0        0        NA                   -3.5736239063e-01    NA          0.0   
0        1        0        0        -3.5736246200e-01    -3.5736246200e-01    0.00e+00    0.1   
An optimal solution satisfying the relative gap tolerance of 

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 3099            
  Cones                  : 515             
  Scalar variables       : 3608            
  Matrix variables       : 0               
  Integer variables      : 257             

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.07
Presolved problem: 2575 variables, 1294 constraints, 5406 non-zeros
Presolved problem: 0 general integer, 257 binary, 2318 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        0        0        NA                   -3.5736032851e-01    NA          0.2   
0        1        0        0        -3.5736247908e-01    -3.5736247908e-01    0.00e+00    0.3   
An optimal solution satisfying the relative gap toleran

In [11]:
save

7×6 Array{Float64,2}:
 0.500005  0.499995  0.0  1.0  1.0  0.103124
 0.500009  0.499991  0.0  1.0  1.0  0.084249
 0.500027  0.499973  0.0  1.0  1.0  0.118458
 0.500005  0.499995  0.0  1.0  1.0  0.337485
 0.499956  0.500044  0.0  1.0  1.0  0.99265 
 0.500017  0.499983  0.0  1.0  1.0  2.58429 
 0.500046  0.499954  0.0  1.0  1.0  7.49789 

In [12]:
function f(x)
    theta = [-2.163, -2.623]
    c = 1-exp(-30*exp(theta[1]+theta[2]*x))
    f = [1,x]
    return sqrt(c)*f
end
ex1 = example(2,[0,1],f)

n = [16; 32; 64; 128; 256; 512; 1024]
save = zeros(length(n), 2*2+2)
for i in 1:length(n)
    t1 = time()
    misocp(n[i],2,ex1)
    solve!(prob, MosekSolver())
    t2 = time()
    cc = w.value[w.value.>0]
    cc = [cc; x[getindex.(findall(x->x>0, w.value),1)]]
    cc = [cc; (prob.optval^2/0.054469214464501994)^(1/2)]
    cc = [cc; t2-t1]
    save[i,:] = cc
end

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 219             
  Cones                  : 35              
  Scalar variables       : 248             
  Matrix variables       : 0               
  Integer variables      : 17              

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.00
Presolved problem: 175 variables, 94 constraints, 366 non-zeros
Presolved problem: 0 general integer, 17 binary, 158 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        0        0        NA                   -2.3325012491e-01    NA          0.0   
0        1        0        0        -2.3324877272e-01    -2.3325012491e-01    5.80e-04    0.0   
An optimal solution satisfying the relative gap tolerance of 

  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 3099            
  Cones                  : 515             
  Scalar variables       : 3608            
  Matrix variables       : 0               
  Integer variables      : 257             

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.08
Presolved problem: 2575 variables, 1294 constraints, 5406 non-zeros
Presolved problem: 0 general integer, 257 binary, 2318 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        0        0        NA                   -2.3338404642e-01    NA          0.1   
0        1        0        0        -2.0572803238e-05    -2.3338404642e-01    1.13e+06    0.5   
0        1        0        0        -2.3338595612e-01    -2.333

In [13]:
save

7×6 Array{Float64,2}:
 0.500028  0.499972  0.0  0.875     0.99941    0.056695 
 0.499999  0.500001  0.0  0.90625   0.999975   0.0465961
 0.500014  0.499986  0.0  0.90625   0.999975   0.206446 
 0.500004  0.499996  0.0  0.898438  0.999995   0.565492 
 0.499988  0.500012  0.0  0.902344  0.999998   1.66675  
 0.500005  0.499995  0.0  0.900391  1.0        3.70441  
 0.499971  0.500029  0.0  0.900391  1.0       12.6027   