In [1]:
include("functions-Copy1.jl")

function f(x)
    theta = [0.05884, 4.298, 21.8]
    c1 = x*theta[3]*exp(-theta[1]*x)
    c2 = -x*theta[3]*exp(-theta[2]*x) 
    c3 = exp(-theta[2]*x)-exp(-theta[1]*x)
    return [c1; c2; c3]
end

ex1 = example(3,[0,30],f)

example(3, [0, 30], f)

In [21]:
res[findall(x->x>10^-4, res[:,1]),:]

5×2 Array{Float64,2}:
 0.333332      0.2
 0.333325      1.4
 0.000237661  18.3
 0.331934     18.4
 0.000980286  18.5

In [15]:
res[findall(x->x>0, res[:,1]),:]

301×2 Array{Float64,2}:
 4.39971e-9   0.0
 1.17623e-8   0.1
 0.333332     0.2
 1.64768e-7   0.3
 2.79923e-8   0.4
 1.78572e-8   0.5
 1.67939e-8   0.6
 1.93915e-8   0.7
 2.55707e-8   0.8
 3.73817e-8   0.9
 6.05482e-8   1.0
 1.14775e-7   1.1
 3.13083e-7   1.2
 ⋮               
 1.60417e-8  28.9
 1.58136e-8  29.0
 1.55917e-8  29.1
 1.53757e-8  29.2
 1.51653e-8  29.3
 1.49605e-8  29.4
 1.4761e-8   29.5
 1.45666e-8  29.6
 1.43772e-8  29.7
 1.41926e-8  29.8
 1.40125e-8  29.9
 1.38369e-8  30.0

In [14]:
res = misocp(ex1,300,0)[1]

MOSEK warning 705: #224 (nearly) zero elements are specified in sparse row ''(2) of matrix 'A'.
MOSEK warning 705: #224 (nearly) zero elements are specified in sparse row ''(5) of matrix 'A'.
MOSEK warning 705: #224 (nearly) zero elements are specified in sparse row ''(8) of matrix 'A'.


┌ Warning: Problem status Stall; solution may be inaccurate.
└ @ Convex /DATA/home/ppinsm/.julia/packages/Convex/6NNC8/src/solution.jl:51


301×2 Array{Float64,2}:
 4.39971e-9   0.0
 1.17623e-8   0.1
 0.333332     0.2
 1.64768e-7   0.3
 2.79923e-8   0.4
 1.78572e-8   0.5
 1.67939e-8   0.6
 1.93915e-8   0.7
 2.55707e-8   0.8
 3.73817e-8   0.9
 6.05482e-8   1.0
 1.14775e-7   1.1
 3.13083e-7   1.2
 ⋮               
 1.60417e-8  28.9
 1.58136e-8  29.0
 1.55917e-8  29.1
 1.53757e-8  29.2
 1.51653e-8  29.3
 1.49605e-8  29.4
 1.4761e-8   29.5
 1.45666e-8  29.6
 1.43772e-8  29.7
 1.41926e-8  29.8
 1.40125e-8  29.9
 1.38369e-8  30.0

In [2]:
misocp(ex1,300,3)

MOSEK warning 705: #224 (nearly) zero elements are specified in sparse row ''(605) of matrix 'A'.
MOSEK warning 705: #224 (nearly) zero elements are specified in sparse row ''(608) of matrix 'A'.
MOSEK warning 705: #224 (nearly) zero elements are specified in sparse row ''(611) of matrix 'A'.


([0.3333749109767016 0.2; 0.3334485702405393 1.4; 0.3331764646600157 18.4], 11.669027181266385)

In [31]:
using BenchmarkTools

In [32]:
@benchmark misocp(ex1,300,3)


MOSEK warning 705: #224 (nearly) zero elements are specified in sparse row ''(605) of matrix 'A'.
MOSEK warning 705: #224 (nearly) zero elements are specified in sparse row ''(608) of matrix 'A'.
MOSEK warning 705: #224 (nearly) zero elements are specified in sparse row ''(611) of matrix 'A'.
MOSEK warning 705: #224 (nearly) zero elements are specified in sparse row ''(605) of matrix 'A'.
MOSEK warning 705: #224 (nearly) zero elements are specified in sparse row ''(608) of matrix 'A'.
MOSEK warning 705: #224 (nearly) zero elements are specified in sparse row ''(611) of matrix 'A'.
MOSEK warning 705: #224 (nearly) zero elements are specified in sparse row ''(605) of matrix 'A'.
MOSEK warning 705: #224 (nearly) zero elements are specified in sparse row ''(608) of matrix 'A'.
MOSEK warning 705: #224 (nearly) zero elements are specified in sparse row ''(611) of matrix 'A'.
MOSEK warning 705: #224 (nearly) zero elements are specified in sparse row ''(605) of matrix 'A'.
MOSEK warning 705: #

BenchmarkTools.Trial: 
  memory estimate:  1.11 GiB
  allocs estimate:  1186012
  --------------
  minimum time:     2.441 s (13.67% GC)
  median time:      2.591 s (16.57% GC)
  mean time:        2.591 s (16.57% GC)
  maximum time:     2.740 s (19.15% GC)
  --------------
  samples:          2
  evals/sample:     1

In [24]:
res[1]

3×2 Array{Float64,2}:
 0.333375   0.2
 0.333449   1.4
 0.333176  18.4

In [25]:
res[2]

11.669027181266385

In [26]:
11.669027181266385 / 11.738774947515308

0.9940583436891184

In [22]:
11.66977965619733 /  11.738774947515308

0.9941224453466004

In [14]:
w.value[w.value.>0 ]

UndefVarError: UndefVarError: w not defined

In [15]:
x[getindex.(findall(x->x>0, w.value),1)]

UndefVarError: UndefVarError: w not defined

In [5]:
prob.optval^4

35.49286878310965

In [6]:
prob.optval^4/1617.5895386975224

0.02194182636201294

In [7]:
n = [16; 32; 64; 128; 256; 512; 1024]
save = zeros(length(n), 3*2+2)
for i in 1:length(n)
    t1 = time()
    misocp(n[i],3,ex1)
    solve!(prob, MosekSolver())
    t2 = time()
    cc = w.value[w.value.>0]
    cc = [cc; x[getindex.(findall(x->x>0, w.value),1)]]
    cc = [cc; (prob.optval^4/1617.5895386975224)^(1/3)]
    cc = [cc; t2-t1]
    save[i,:] = cc
end

MOSEK warning 705: #12 (nearly) zero elements are specified in sparse row ''(2) of matrix 'A'.
MOSEK warning 705: #12 (nearly) zero elements are specified in sparse row ''(5) of matrix 'A'.
MOSEK warning 705: #12 (nearly) zero elements are specified in sparse row ''(8) of matrix 'A'.
Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 305             
  Cones                  : 54              
  Scalar variables       : 365             
  Matrix variables       : 0               
  Integer variables      : 17              

Optimizer started.
Mixed integer optimizer started.
Threads used: 24
Presolve started.
Presolve terminated. Time = 0.00
Presolved problem: 249 variables, 135 constraints, 517 non-zeros
Presolved problem: 0 general integer, 17 binary, 232 continuous
Clique table size: 0
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELA

0        1        0        0        -1.7570195305e-03    -6.3406736756e+00    3.61e+05    0.4   
0        1        0        0        -6.3405277304e+00    -6.3406736756e+00    2.30e-03    0.7   
An optimal solution satisfying the relative gap tolerance of 1.00e-02(%) has been located.
The relative gap is 2.30e-03(%).

Objective of best integer solution : -6.340527730371e+00     
Best objective bound               : -6.340673675635e+00     
Construct solution objective       : Not employed
Construct solution # roundings     : 0
User objective cut value           : 0
Number of cuts generated           : 0
Number of branches                 : 0
Number of relaxations solved       : 1
Number of interior point iterations: 30
Number of simplex iterations       : 0
Time spend presolving the root     : 0.02
Time spend in the heuristic        : 0.00
Time spend in the sub optimizers   : 0.00
  Time spend optimizing the root   : 0.06
Mixed integer optimizer terminated. Time: 0.71

Optimizer termina

In [8]:
save[:,1:6]

7×6 Array{Float64,2}:
 0.333339  0.333353  0.333308  1.875     3.75     20.625 
 0.33334   0.333354  0.333306  0.9375    1.875    18.75  
 0.333043  0.333381  0.333576  0.46875   1.40625  18.2813
 0.333344  0.333381  0.333275  0.234375  1.40625  18.5156
 0.333367  0.333394  0.33324   0.234375  1.40625  18.3984
 0.333313  0.333333  0.333354  0.234375  1.40625  18.457 
 0.333376  0.333349  0.333275  0.234375  1.40625  18.4277

In [9]:
save[:,7:8]

7×2 Array{Float64,2}:
 0.0308535   0.320519
 0.321916    0.271826
 0.79777     0.410691
 0.999719    1.02846 
 0.999728    2.46409 
 0.999775    6.77908 
 0.999759   17.7544  