In [1]:
include("functions.jl")

psox (generic function with 1 method)

In [2]:
function f(x)
    theta = [0.05884, 4.298, 21.8]
    c1 = x[1]*theta[3]*exp(-theta[1]*x[1])
    c2 = -x[1]*theta[3]*exp(-theta[2]*x[1]) 
    c3 = exp(-theta[2]*x[1])-exp(-theta[1]*x[1])
    return [c1; c2; c3]
end

N = 3
dim = 1
design = [0 30]
niter = 2^10
nptc = 2^10

psox(N, f, dim, design, niter, nptc)

....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
...........................................................................................

3-element Array{Any,1}:
 11.73877494752132                                                                                                                                                                     
   [18.4168; 1.38859; 0.228772]                                                                                                                                                        
   [11.3309, 11.3309, 11.3309, 11.3309, 11.3309, 11.476, 11.476, 11.476, 11.6028, 11.6028  …  11.7388, 11.7388, 11.7388, 11.7388, 11.7388, 11.7388, 11.7388, 11.7388, 11.7388, 11.7388]

In [3]:
N = 3*(1:20)
result1 = zeros(20)
timeresult1 = zeros(20)
for i = 1:20
    t1 = time()
    result1[i] = psox(N[i], f, dim, design, niter, nptc)[1]
    t2 = time()
    timeresult1[i] = t2 -t1
end

....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
...........................................................................................

....................................................................................................
....................................................................................................
....................................................................................................
........................PSO iteration complete
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
............................................

....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
........................PSO iteration complete
....................................................................................................
....................................................................................................
....................................................................................................
............................................

In [4]:
function f(x)
    theta = [3,-5,0]
    c = exp(theta[1]+theta[2]*(x[1]-theta[3])^2)
    f = [1,(x[1]-theta[3])^2,2*theta[2]*(theta[3]-x[1]) ]
    return sqrt(c)/(1+c)*f
end

N = 4
dim = 1
design = [-1 1]
niter = 2^10
nptc = 2^10

psox(N, f, dim, design, niter, nptc)

....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
...........................................................................................

3-element Array{Any,1}:
 0.26977044278635043                                                                                                                                                                               
  [0.933599; 0.623313; -0.933599; -0.623313]                                                                                                                                                       
  [0.269087, 0.269087, 0.269087, 0.269087, 0.269087, 0.269087, 0.269087, 0.269087, 0.269087, 0.269449  …  0.26977, 0.26977, 0.26977, 0.26977, 0.26977, 0.26977, 0.26977, 0.26977, 0.26977, 0.26977]

In [5]:
N = 4*(1:20)
result2 = zeros(20)
timeresult2 = zeros(20)
for i = 1:20
    t1 = time()
    result2[i] = psox(N[i], f, dim, design, niter, nptc)[1]
    t2 = time()
    timeresult2[i] = t2 -t1
end

....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
...........................................................................................

....................................................................................................
....................................................................................................
....................................................................................................
........................PSO iteration complete
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
............................................

....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
........................PSO iteration complete
....................................................................................................
....................................................................................................
....................................................................................................
............................................

In [6]:
function f(x)
    theta = [.2; .2; .2]
    c = theta[1]*exp(theta[2]*x[1]) + (1-theta[1])*exp(-theta[3]*x[1])
    f = [1; (exp(theta[2]*x[1]) - exp(-theta[3]*x[1]))/c; theta[1]*x*exp(theta[2]*x[1])/c; -(1-theta[1])*x[1]*exp(-theta[3]*x[1])/c]
    return f
end

N = 4
dim = 1
design = [0 10]
niter = 2^10
nptc = 2^10

psox(N, f, dim, design, niter, nptc)

....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
...........................................................................................

3-element Array{Any,1}:
 0.6359526427973213                                                                                                                                                                                          
  [6.70741; 0.0; 10.0; 2.65993]                                                                                                                                                                              
  [0.556024, 0.635174, 0.635721, 0.635721, 0.635721, 0.635721, 0.635721, 0.635891, 0.635892, 0.635892  …  0.635953, 0.635953, 0.635953, 0.635953, 0.635953, 0.635953, 0.635953, 0.635953, 0.635953, 0.635953]

In [ ]:
N = 4*(1:20)
result3 = zeros(20)
timeresult3 = zeros(20)
for i = 1:20
    t1 = time()
    result3[i] = psox(N[i], f, dim, design, niter, nptc)[1]
    t2 = time()
    timeresult3[i] = t2 -t1
end

....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
...........................................................................................

....................................................................................................
....................................................................................................
....................................................................................................
........................PSO iteration complete
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
............................................